import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { SidebarDemo } from "@/components/shared/SidebarDemo";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} antialiased`}>
        <SidebarDemo>
          <div className="bg-[#f3f4f8]  p-2 md:p-10 h-screen overflow-auto">
            {children}
          </div>
        </SidebarDemo>
      </body>
    </html>
  );
}
